# Hyperparameter sweep configuration
# Define parameters to sweep over and their possible values

sweep_name: "initialization_sweep_test"  # Name of the sweep

parameters:
  # Example of sweeping over learning rates
  # training.learning_rate:
  #   values: [0.0001, 0.0003, 0.0006, 0.001]
  
  # Example of sweeping over batch sizes
  # training.batch_size:
  #   values: [16, 32, 64]
  
  # Example of sweeping over number of epochs
  # training.num_epochs:
  #   values: [1, 2]
  
  # Example of sweeping over initialization parameters
  initialization.init_std:
    values: [0.01, 0.02]
  
  initialization.init_mean:
    values: [0.0]

# Strategy for selecting combinations (grid, random)
strategy: "grid" 

# Number of runs to perform with different combinations if strategy is random
num_runs: 2